apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  DB_HOST: "ZGF0YWJhc2Utc2VydmljZQ=="   # database-service
  DB_PORT: "MzMwNg=="                    # 3306
  DB_USER: "Y2hhdHVzZXI="               # chatuser
  DB_PASSWORD: "Y2hhdDEyMw=="           # chat123
  DB_NAME: "Y2hhdGZsb3c="               # chatflow
 
