apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Y2hhdDEyMw=="
  MYSQL_DATABASE: "Y2hhdGRi"
  MYSQL_USER: "Y2hhdHVzZXI="
  MYSQL_PASSWORD: "Y2hhdDEyMw==" 
