apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: backend
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  replicas: 2
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        envFrom:
        - secretRef:
            name: database-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /usr/lib/mysql
        - name: init-sql          
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-sql           
        configMap:
          name: init-sql-configmap
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
