apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.secret.data.DB_HOST }}   # database-service
  DB_PORT: {{ .Values.secret.data.DB_PORT }}                    # 3306
  DB_USER: {{ .Values.secret.data.DB_USER }}               # chatuser
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD }}           # chat123
  DB_NAME: {{ .Values.secret.data.DB_NAME }}               # chatflow
 
