apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
